config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "courses#index"
  resources :questions, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :edit, :update, :show]
  resources :courses, except: [:destroy]
  get "courses/:id/student/new", to: "courses#new_student", as: "new_student"
  post "courses/:id/student", to: "courses#create_student"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :sessions
	belongs_to :teacher # belongs to teacher sti not student
	has_and_belongs_to_many :students, :join_table => "courses_students"
	validates_presence_of :name, :user_id
	validates_uniqueness_of :name

end

app/models/generator.rb
class Generator
  def self.alphanumeric_string(length_of_string)
    range = [*'0'..'9', *'a'..'z', *'A'..'Z']
    Array.new(length_of_string){range.sample}.join
  end

  def self.alphabetic_string(length_of_string)
    range = [*'a'..'z', *'A'..'Z']
    Array.new(length_of_string){range.sample}.join
  end

  def self.sentence(num_of_words)
    "#{num_of_words.times.map {Generator.alphabetic_string([*4..9].sample)}.join(" ")}."
  end

  def self.paragraph(num_of_sentences)
    "#{num_of_sentences.times.map {Generator.sentence([*7..13].sample)}.join(" ")}\n"
  end

  def self.name_of(obj, num='', length=6)
    "#{obj.capitalize} #{num} #{Generator.alphabetic_string(length)}"
  end

  def self.date(month, day, year)
    "#{month} #{day}, #{year}"
  end

  def self.email()
    "#{Generator.alphabetic_string(8)}@#{Generator.alphabetic_string(3)}.com"
  end

  def self.student_email(num)
    "email#{num}@student.com"
  end

  @num = 0
  def self.num
    @num = @num + 1
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :session

  validates_presence_of :question, :session_id
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :course
  has_many :questions

  validates_presence_of :name, :date, :sequence_num, :course_id
  validates_uniqueness_of :sequence_num,  { :scope =>  :course_id }
  validates_uniqueness_of :date, { :scope => :course_id }
  validates_uniqueness_of :name, { :scope => :course_id }

  #validates_uniqueness_of :model_name, :scope => {:brand_id, :fuel_type_id}
end

app/models/student.rb
class Student < User
  has_and_belongs_to_many :courses, :join_table => "courses_students"#, association_foreign_key: :user_id
end

app/models/teacher.rb
class Teacher < User
  has_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  validates :name,
      presence: true,
      length: {minimum: 8, maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, :alert => exception.message
  # end

  #what is the rails 4 way to prevent password logging?
  #rails 2
  #filter_parameter_logging :password, :password_confirmation
  #rails 3
  #config.filter_parameters += [:password, :password_confirmation]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  def index
    @courses = Course.all # where session is not 0
  end

  def show
    @course = Course.find(params[:id])
    @sessions = Session.where(course_id: @course.id)
    @students = @course.students
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if Course.update(course_params)
      redirect_to course_path(@course)
    else
      render :edit
    end
  end

  def new_student
  end

  def create_student
    #need course id passed through params
    course = Course.find(params[:id])
    pass = "p@s$w0rd"
    student = Student.new(name: "Student #{course.students.count + 1}", email: params[:student][:email], password: pass, password_confirmation: pass)
    if student.save
      course.students.push(student)
      redirect_to course_path(course)
    else
      render :new_student
    end
  end

  private
  
  def student_params
    params.require(:student).permit(:email) 
  end

  def course_params
    params.require(:course).permit(:name, :user_id, :start_date, :end_date)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @session = Session.find(@question.session_id)
    if @question.save
      redirect_to session_path(@session)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path(@question)
    else
      render :edit
    end
  end

  def question_params
    params.require(:question).permit(:question, :answer, :session_id)
    # always require session_id? teacher should be able to move a question to a different session
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  def show
    @questions = Question.where(session_id: params[:id]).where.not( answer: nil)
    @session = Session.find(params[:id])
  end

  def new
    @session = Session.new
    @courses = Course.where(user_id: current_user.id)
  end

  def create
    @session = Session.new(session_params)
    if @session.save
      redirect_to course_path(@session.course_id)
    else
      render :new
    end
  end

  def edit
    @session = Session.find(params[:id])
  end

  def update
    @session = Session.find(params[:id])
    if @session.update(session_params)
      redirect_to session_path(@session) #should go to show page?
    else
      render :edit
    end
  end

  def session_params
    params.require(:session).permit(:name, :date, :sequence_num, :course_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#
#   def show
#     @user = User.find(params[:id])
#   end
#
#   def new
#     @user = User.new
#   end
#
#   def create
#     @user = User.new(user_params)
#     if @user.save
#       redirect_to user_path(@user)
#     else
#       render :new
#     end
#   end
#
#   def edit
#     @user = User.find(params[:id])
#   end
#
#
#   def update
#   end
#
#   def destroy
#     @user = User.find(params[:id])
#     @user.destroy
#     #redirect_to users_path
#   end
#
#   def user_params
#     params.require(:user).permit(:name, :email, :password, :password_confirmation)
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/courses/_form.html.erb
<ul>
<% @course.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>


<%= form_for(@course) do |f| %>

  <%= f.label :user_id %>
  <%= f.number_field :user_id %>
  <br>

  <%= f.label :name %>
  <%= f.text_area :name %>
  <br>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>
  <br>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>
  <br>

  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h2> Edit Course </h2>

<%= render 'form' %>

app/views/courses/index.html.erb
<!-- if current user is truthy, show the user his or her courses -->

<h2> All courses on Teach.r </h2>
<table>
<% @courses.each do |course| %>
<tr> 
	<td> <%= link_to course.name, course_path(course) %> </td> 
	<td> <%= course.sessions.count %> sessions </td> 
	<td> Teacher: <%= Teacher.find(course.user_id).name %> </td> 
</tr>
<% end %>
</table>

app/views/courses/new.html.erb
<h2> New Course </h2>

<%= render 'form' %>

app/views/courses/new_student.html.erb
<!-- How do I get errors shown here? -->

<%= form_tag("/courses/#{params[:id]}/student", method: "post") do %>
  <%= label_tag('student[email]', "Email") %>
  <%= text_field_tag('student[email]') %>
  <%= submit_tag('New Student') %>
<% end %>

app/views/courses/show.html.erb
<h2> <%= @course.name %> </h2>

<h2> Sessions </h2> 
<%= link_to 'New Session', new_session_path, :class => 'button-link' %>
<table>
<% @sessions.each do |session| %>
<tr> 
	<td> <%= link_to session.name, session_path(session) %> </td> 
	<td> <%= session.questions.count %> questions </td> 
</tr>
<% end %>
</table>


<h2> Students </h2>
<table>
<%= link_to 'New Student', new_student_path, :class => 'button-link' %>
<% @students.each do |student| %>
<tr><td> <%= student.name %> </tr></td>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeachrApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'skeleton', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<header class="sixteen columns">
  <h1 class="">
    teach.r
  </h1>

  <nav class="">

  <% if user_signed_in? %>
    <%= link_to 'New Course', new_course_path %>
    <%= link_to 'All Courses', courses_path %>
    <%= link_to "#{current_user.name} (edit)", edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout #{current_user.type}", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  
  <% else %>
    <%= link_to 'New Course', new_course_path %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    </nav>
  <% end %>
</nav>
</header>



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


  <%= yield %>

</div>
</body>
</html>

app/views/questions/_form.html.erb
<ul>
<% @question.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>


<%= form_for(@question) do |f| %>

  <%= f.label :question %>
  <%= f.text_area :question %>
  <br>

  <%= f.label :answer %>
  <%= f.text_area :answer %>
  <br>

  <%= f.label :session_id %>
  <%= f.number_field :session_id %>
  <br>

  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>

<%= render 'form' %>

app/views/questions/new.html.erb
<h2> New Question </h2>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<ul>
<% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', tractors_path %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>